# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tFp9vEykvW6Lz82rQpjpnh_gJsw9TJ_s
"""

# --- DEMOSTRACIÓN DEL CASO DE USO ---
if __name__ == "__main__":
    # 1. ENTRADA: DataFrame de la librería
    libreria_df = generar_caso_de_uso_recomendar_libros_similares()
    libro_input = "Cien años de soledad"

    print("### CATÁLOGO DISPONIBLE ###")
    print(libreria_df[['titulo']])
    print(f"\nLibro que el usuario leyó: '{libro_input}'")
    print("-" * 50)

    # 2. EJECUCIÓN: Obtener recomendaciones
    recomendaciones = recomendar_libros_similares(libreria_df, libro_input)

    # 3. SALIDA: Lista de strings con los títulos
    print("### SALIDA DE LA FUNCIÓN (Recomendaciones) ###")
    print(f"Tipo de dato: {type(recomendaciones)}")
    print(f"Valores: {recomendaciones}")

    # Ejemplo adicional con Ciencia Ficción
    print("\nPrueba con Ciencia Ficción ('Fundación'):")
    print(recomendar_libros_similares(libreria_df, "Fundación"))