# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10aQRjMkKB2eJrI2ENjNW8Xf3RfGgNKcG
"""

# --- CASO DE USO ---
if __name__ == "__main__":
    # 1. Obtención de datos (Entrada)
    df_fabrica = generar_caso_de_uso_clasificar_piezas_produccion()

    print("### ESTRUCTURA DE ENTRADA (Primeras 5 filas) ###")
    print(df_fabrica.head())
    print("-" * 50)

    # 2. Simular nuevos datos que llegan de la línea de producción (sin la etiqueta)
    # Tomamos 3 ejemplos nuevos manualmente
    nuevos_sensores = pd.DataFrame({
        'largo': [15.2, 32.5, 48.1],
        'ancho': [7.5, 16.1, 24.0],
        'peso': [18.0, 39.2, 57.5],
        'densidad': [6.1, 7.8, 8.5],
        'resistencia': [14.4, 31.3, 46.0]
    })

    # 3. Ejecución de la función (Proceso y Salida)
    resultado = clasificar_piezas_produccion(df_fabrica, nuevos_sensores)

    print("### DATOS DE ENTRADA PARA PREDICCIÓN ###")
    print(nuevos_sensores)
    print("\n### SALIDA DE LA FUNCIÓN (Predicciones) ###")
    print(f"Tipo de dato: {type(resultado)}")
    print(f"Valores resultantes: {resultado}")
    # Nota: 0=Pequeña, 1=Mediana, 2=Grande