# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bb0kn3ndSNKplCZDuzx70GQDz7J4f4gc
"""

Python
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

def generar_caso_de_uso_predecir_potencia_solar():
    """
    Genera un DataFrame sintético con datos de sensores solares.

    Variables:
    - radiacion_uv: 0 a 11 (Índice UV)
    - indice_nubosidad: 0 a 100 (%)
    - temperatura_panel: 20 a 70 (°C)
    - potencia_kw: Variable dependiente (objetivo)
    """
    np.random.seed(42)
    n_registros = 200

    uv = np.random.uniform(1, 11, n_registros)
    nubes = np.random.uniform(0, 100, n_registros)
    temp = 25 + (uv * 2) + np.random.normal(0, 5, n_registros)

    # La potencia sube con UV, baja con nubes y tiene ruido térmico
    # Fórmula base: Potencia = (UV * 50) - (Nubes * 0.5) + Ruido
    potencia = (uv * 45) - (nubes * 0.3) + (temp * 0.1) + np.random.normal(0, 10, n_registros)
    # Asegurar que no haya valores negativos de potencia
    potencia = np.clip(potencia, 0, None)

    df = pd.DataFrame({
        'radiacion_uv': uv,
        'indice_nubosidad': nubes,
        'temperatura_panel': temp,
        'potencia_kw': potencia
    })

    return df

def predecir_potencia_solar(df):
    """
    Entrena un modelo de Random Forest para predecir la generación de energía.

    Entrada: pd.DataFrame con features y target.
    Salida: Tupla (modelo_entrenado, mae_score).
    """
    # 1. Separación de variables
    X = df[['radiacion_uv', 'indice_nubosidad', 'temperatura_panel']]
    y = df['potencia_kw']

    # 2. Split de datos (80% tren, 20% test)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # 3. Configuración del Bosque Aleatorio
    # Usamos 100 árboles para manejar la variabilidad de los datos
    modelo = RandomForestRegressor(n_estimators=100, random_state=42)

    # 4. Entrenamiento
    modelo.fit(X_train, y_train)

    # 5. Evaluación
    predicciones = modelo.predict(X_test)
    mae = mean_absolute_error(y_test, predicciones)

    return modelo, mae

# --- DEMOSTRACIÓN DEL CASO DE USO ---
if __name__ == "__main__":
    # PASO 1: Generar los datos de entrada
    datos_parque = generar_caso_de_uso_predecir_potencia_solar()

    print("### DATOS DE ENTRADA (Dataset de Sensores) ###")
    print(datos_parque.head())
    print(f"\nDimensiones del DataFrame: {datos_parque.shape}")
    print("-" * 60)

    # PASO 2: Invocar la función de solución
    modelo_final, error_obtenido = predecir_potencia_solar(datos_parque)

    # PASO 3: Mostrar la salida explícita
    print("### RESULTADO DE LA FUNCIÓN ###")
    print(f"Tipo de objeto del modelo: {type(modelo_final)}")
    print(f"Error Absoluto Medio (MAE): {error_obtenido:.4f} kW")

    # Ejemplo de una predicción individual
    dato_nuevo = [[8.5, 15.0, 42.0]] # [UV, Nubosidad, Temp]
    prediccion_puntual = modelo_final.predict(dato_nuevo)
    print(f"\nPredicción para [UV: 8.5, Nubes: 15%, Temp: 42°C]: {prediccion_puntual[0]:.2f} kW")