# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pbT0BOvbgjYVTtbalXUub0IlJrB5Zp2a
"""

# --- EJECUCIÓN DEL CASO DE USO ---

# 1. ENTRADA: Se genera el DataFrame 'df_trafico'
df_trafico = generar_caso_de_uso_detectar_ataque_ddos()

# 2. INVOCACIÓN (Lo que el alumno debe resolver):
# lista_ips_sospechosas = detectar_ataque_ddos(df_trafico)

# 3. SALIDA ESPERADA:
# El resultado debe ser una lista con la(s) IP(s) que superan el umbral (media + 3*std).
# Ejemplo: ['172.16.0.45']

# Visualización de la entrada (df_trafico) en el Notebook
df_trafico.head()